# Generated by Django 3.2.12 on 2023-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariossena',
            name='fotoUsuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarioFoto/'),
        ),
    ]
