# Generated by Django 3.0.3 on 2023-10-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0003_auto_20230926_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='elementoSerial',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuarioSena',
        ),
    ]
