# Generated by Django 3.0.3 on 2023-10-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0004_auto_20231007_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariossena',
            old_name='apellido',
            new_name='apellidoo',
        ),
    ]
